"""add language to posts

Revision ID: 772d86e56baa
Revises: f05a7a5a1bcb
Create Date: 2019-06-04 11:58:06.362479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772d86e56baa'
down_revision = 'f05a7a5a1bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
